# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79252673745894b33179f707df65b3248f272f2e46bfa2078120f8c252f7e59331033872fe13be2b2259f0b01fc7d73d6d8e58c3b54969ff67d348bef69f959f

test:
  secret_key_base: 51273e88b99c66c8b3c1bfec07acd6decb4c824853659d0323bf3fd0927909240544f0f6a6bb7f2bed8e8761fd8439a43ae31f2a06571c8ad95282f73ed15c84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
